export const nacionalidades = [
    { id :0, name : ''},
    { id :101, name : 'namibiana'},
    { id :103, name : 'angolesa'},
    { id :104, name : 'argeliana'},
    { id :105, name : 'de bennin'},
    { id :106, name : 'botswanesa'},
    { id :107, name : 'burundesa'},
    { id :108, name : 'de cabo verde'},
    { id :109, name : 'comorense'},
    { id :110, name : 'congolesa'},
    { id :111, name : 'marfileña'},
    { id :112, name : 'chadiana'},
    { id :113, name : 'de djibouti'},
    { id :114, name : 'egipcia'},
    { id :115, name : 'etiope'},
    { id :116, name : 'gabonesa'},
    { id :117, name : 'gambiana'},
    { id :118, name : 'ghanata'},
    { id :119, name : 'guinea'},
    { id :120, name : 'guinea'},
    { id :121, name : 'guinea ecuatoriana'},
    { id :122, name : 'libia'},
    { id :123, name : 'keniana'},
    { id :124, name : 'lesothense'},
    { id :125, name : 'liberiana'},
    { id :127, name : 'malawiana'},
    { id :128, name : 'maliense'},
    { id :129, name : 'marroqui'},
    { id :130, name : 'mauriciana'},
    { id :131, name : 'mauritana'},
    { id :132, name : 'mozambiqueña'},
    { id :133, name : 'nigerina'},
    { id :134, name : 'nigeriana'},
    { id :135, name : 'centro africana'},
    { id :136, name : 'camerunesa'},
    { id :137, name : 'tanzaniana'},
    { id :139, name : 'rwandesa'},
    { id :140, name : 'del sahara'},
    { id :141, name : 'de santo tome'},
    { id :142, name : 'senegalesa'},
    { id :143, name : 'de seychelles'},
    { id :144, name : 'sierra leonesa'},
    { id :145, name : 'somali'},
    { id :146, name : 'sudafricana'},
    { id :147, name : 'sudanesa'},
    { id :148, name : 'swazi'},
    { id :149, name : 'togolesa'},
    { id :150, name : 'tunecina'},
    { id :151, name : 'ugandesa'},
    { id :152, name : 'zairana'},
    { id :153, name : 'zambiana'},
    { id :154, name : 'de zimbawi'},
    { id :201, name : 'argentina'},
    { id :202, name : 'bahameña'},
    { id :203, name : 'de barbados'},
    { id :204, name : 'beliceña'},
    { id :205, name : 'boliviana'},
    { id :206, name : 'brasileña'},
    { id :207, name : 'canadiense'},
    { id :208, name : 'colombiana'},
    { id :209, name : 'costarricense'},
    { id :210, name : 'cubana'},
    { id :211, name : 'chilena'},
    { id :212, name : 'dominica'},
    { id :214, name : 'salvadoreña'},
    { id :215, name : 'estadounidense'},
    { id :216, name : 'granadina'},
    { id :217, name : 'guatemalteca'},
    { id :218, name : 'britanica'},
    { id :219, name : 'guyanesa'},
    { id :220, name : 'haitiana'},
    { id :221, name : 'hondureña'},
    { id :222, name : 'jamaiquina'},
    { id :223, name : 'mexicana'},
    { id :224, name : 'nicaraguense'},
    { id :225, name : 'panameña'},
    { id :226, name : 'paraguaya'},
    { id :227, name : 'peruana'},
    { id :228, name : 'puertorriqueña'},
    { id :229, name : 'dominicana'},
    { id :230, name : 'santa luciense'},
    { id :231, name : 'surinamense'},
    { id :232, name : 'trinitaria'},
    { id :233, name : 'uruguaya'},
    { id :234, name : 'venezolana'},
    { id :299, name : 'americana'},
    { id :301, name : 'afgana'},
    { id :303, name : 'de bahrein'},
    { id :305, name : 'bhutanesa'},
    { id :306, name : 'birmana'},
    { id :307, name : 'norcoreana'},
    { id :308, name : 'sudcoreana'},
    { id :309, name : 'china'},
    { id :310, name : 'chipriota'},
    { id :311, name : 'arabe'},
    { id :312, name : 'filipina'},
    { id :313, name : 'hindu'},
    { id :314, name : 'indonesa'},
    { id :315, name : 'iraqui'},
    { id :316, name : 'irani'},
    { id :317, name : 'israeli'},
    { id :318, name : 'japonesa'},
    { id :319, name : 'jordana'},
    { id :320, name : 'camboyana'},
    { id :321, name : 'kuwaiti'},
    { id :322, name : 'libanesa'},
    { id :323, name : 'malasia'},
    { id :324, name : 'maldiva'},
    { id :325, name : 'mongolesa'},
    { id :326, name : 'nepalesa'},
    { id :327, name : 'omanesa'},
    { id :328, name : 'pakistani'},
    { id :329, name : 'del qatar'},
    { id :330, name : 'siria'},
    { id :331, name : 'laosiana'},
    { id :332, name : 'singaporense'},
    { id :334, name : 'tailandesa'},
    { id :335, name : 'taiwanesa'},
    { id :336, name : 'turca'},
    { id :337, name : 'norvietnamita'},
    { id :339, name : 'yemeni'},
    { id :401, name : 'albanesa'},
    { id :403, name : 'alemana'},
    { id :404, name : 'andorrana'},
    { id :405, name : 'austriaca'},
    { id :406, name : 'belga'},
    { id :407, name : 'bulgara'},
    { id :408, name : 'checoslovaca'},
    { id :409, name : 'danesa'},
    { id :410, name : 'vaticana'},
    { id :411, name : 'española'},
    { id :412, name : 'finlandesa'},
    { id :413, name : 'francesa'},
    { id :414, name : 'griega'},
    { id :415, name : 'hungara'},
    { id :416, name : 'irlandesa'},
    { id :417, name : 'islandesa'},
    { id :418, name : 'italiana'},
    { id :419, name : 'liechtenstense'},
    { id :420, name : 'luxemburguesa'},
    { id :421, name : 'maltesa'},
    { id :422, name : 'monegasca'},
    { id :423, name : 'noruega'},
    { id :424, name : 'holandesa'},
    { id :426, name : 'portuguesa'},
    { id :427, name : 'britanica'},
    { id :428, name : 'sovietica bielorrusa'},
    { id :429, name : 'sovietica ucraniana'},
    { id :430, name : 'rumana'},
    { id :431, name : 'san marinense'},
    { id :432, name : 'sueca'},
    { id :433, name : 'suiza'},
    { id :435, name : 'yugoslava'},
    { id :501, name : 'australiana'},
    { id :502, name : 'fijiana'},
    { id :503, name : 'salomonesa'},
    { id :504, name : 'nauruana'},
    { id :506, name : 'papuense'},
    { id :507, name : 'samoana'},
    { id :667, name : 'eslovaca'},
    { id :609, name : 'burkina faso'},
    { id :621, name : 'estonia'},
    { id :624, name : 'micronecia'},
    { id :625, name : 'reino unido(depen. tet. brit.)'},
    { id :626, name : 'reino unido(brit. del ext.)'},
    { id :627, name : 'reino unido(c. brit. del ext.)'},
    { id :629, name : 'reino unido'},
    { id :642, name : 'kirguistan'},
    { id :645, name : 'lituania '},
    { id :648, name : 'moldovia, republica de'},
    { id :650, name : 'macedonia'},
    { id :668, name : 'eslovenia'},
    { id :684, name : 'eslovaquia'},
]